"""Wire models for the FastAPI AI service boundary (P2.5).

Two cross-team decisions are encoded here. Both were open questions on Day 5
(docs/api_contracts.md marks the whole Spring Boot -> FastAPI section
`PROVISIONAL - REQUIRES TEAM APPROVAL` and asks Person 2 to react); this module
is Person 2's answer, and both need Person 1 + Person 3 sign-off to become
final. See ai_service/README.md for the reasoning in full.

1. **The wire is camelCase.** Person 1's Spring Boot DTOs (ChatRequest /
   ChatResponse) are camelCase and Person 3's ai/contracts.py is snake_case.
   Rather than force a rename on either side, the Python field names stay
   snake_case (matching the frozen contract exactly) and Pydantic serializes
   them to camelCase, so the JSON drops straight into Spring's records with no
   @JsonProperty annotations.

2. **The two delivery-date fields are added here, not in ai/contracts.py.**
   Spring Boot's ChatResponse already carries promisedDeliveryDate /
   revisedDeliveryDate, flagged as a provisional extension, because the UI's
   Impact table (docs/04_ui_ux_design.md §3.2) and the flagship sample
   (docs/problem_statement.md §7) both need them — but CoPilotResponse doesn't
   have them. Person 3 owns ai/contracts.py and "shared contracts may not be
   changed silently" (docs/team_plan.md), so this subclasses CoPilotResponse
   instead of editing it. If Person 3 folds the fields into the frozen contract,
   delete the two declarations below and the subclass collapses to a no-op.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel

from ai.contracts import CoPilotResponse


class _CamelModel(BaseModel):
    """snake_case in Python, camelCase on the wire, accepts both on input."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class AiQueryRequest(_CamelModel):
    """Body of POST /ai/query, sent by Spring Boot (docs/api_contracts.md)."""

    query: str = Field(min_length=1, description="The user's natural-language question.")
    session_id: str | None = Field(
        default=None, description="Conversation session; Spring Boot mints one if absent."
    )
    trace_id: str | None = Field(
        default=None,
        description=(
            "Correlation ID generated by Spring Boot. Threaded through FastAPI -> LangGraph "
            "-> MCP unchanged so audit_log.trace_id can stitch the request back together "
            "(tech-req §9). Echoed back in the response."
        ),
    )


class AiQueryResponse(CoPilotResponse, _CamelModel):
    """CoPilotResponse (frozen, ai/contracts.py) + the correlation envelope and
    the two provisional delivery-date fields Spring Boot's ChatResponse needs.

    Field order/names of the inherited half are the contract — don't shadow them.
    """

    trace_id: str | None = None
    session_id: str | None = None

    # PROVISIONAL — pending Person 3 sign-off; see module docstring.
    promised_delivery_date: str | None = None
    revised_delivery_date: str | None = None
