"""Wire models for the FastAPI AI service boundary (P2.5).

Two cross-team decisions are encoded here. Both were open questions on Day 5
(docs/api_contracts.md marks the whole Spring Boot -> FastAPI section
`PROVISIONAL - REQUIRES TEAM APPROVAL` and asks Person 2 to react); this module
is Person 2's answer, and both need Person 1 + Person 3 sign-off to become
final. See ai_service/README.md for the reasoning in full.

1. **The wire is camelCase.** Person 1's Spring Boot DTOs (ChatRequest /
   ChatResponse) are camelCase and Person 3's ai/contracts.py is snake_case.
   Rather than force a rename on either side, the Python field names stay
   snake_case (matching the frozen contract exactly) and Pydantic serializes
   them to camelCase, so the JSON drops straight into Spring's records with no
   @JsonProperty annotations.

2. **The two delivery-date fields — RESOLVED, folded into CoPilotResponse.**
   Originally added here as a provisional subclass extension (Spring Boot's
   ChatResponse needed promisedDeliveryDate/revisedDeliveryDate before
   CoPilotResponse had them). Person 3 has now folded both fields into the
   frozen contract directly (ai/contracts.py, ai/CONTRACTS.md §8 changelog) —
   pending Person 1 + Person 2 confirmation. The redeclarations that used to
   live on AiQueryResponse below are removed; the fields are inherited as-is.

P1.10 contract-validation fix: `Source` (ai/contracts.py) is a plain
BaseModel with no alias generator, so a bare `list[Source]` field would put
snake_case objects (`document_name`, `doc_id`) inside this otherwise-camelCase
response — Spring's `SourceDto` (camelCase) would silently deserialize every
nested source as all-null. `sources` below overrides the inherited field with
`list[SourceOut]`, the same camelCase-on-the-wire treatment every top-level
field already gets, without editing the frozen `Source` model itself.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel

from ai.contracts import CoPilotResponse


class _CamelModel(BaseModel):
    """snake_case in Python, camelCase on the wire, accepts both on input."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class SourceOut(_CamelModel):
    """Wire shape of ai.contracts.Source — camelCase, so it matches Spring
    Boot's SourceDto and Angular's Source interface like every other field
    here, instead of the frozen model's own snake_case."""

    document_name: str
    snippet: str | None = None
    doc_id: int | None = None
    score: float | None = None


class AiQueryRequest(_CamelModel):
    """Body of POST /ai/query, sent by Spring Boot (docs/api_contracts.md)."""

    query: str = Field(
        min_length=1, description="The user's natural-language question."
    )
    session_id: str | None = Field(
        default=None,
        description="Conversation session; Spring Boot mints one if absent.",
    )
    user_id: str | None = Field(
        default=None,
        description=(
            "Authenticated caller's username, forwarded from Spring Boot's JWT "
            "(Authentication#getName()). CoPilotState.user_id requires a value; "
            "Spring Boot is the only layer that terminates user auth (tech-req §8), "
            "so FastAPI never resolves this itself."
        ),
    )
    trace_id: str | None = Field(
        default=None,
        description=(
            "Correlation ID generated by Spring Boot. Threaded through FastAPI -> LangGraph "
            "-> MCP unchanged so audit_log.trace_id can stitch the request back together "
            "(tech-req §9). Echoed back in the response."
        ),
    )


class AiQueryResponse(CoPilotResponse, _CamelModel):
    """CoPilotResponse (frozen, ai/contracts.py) + the correlation envelope and
    the two provisional delivery-date fields Spring Boot's ChatResponse needs.

    Field order/names of the inherited half are the contract — don't shadow them.
    """

    trace_id: str | None = None
    session_id: str | None = None

    # Overrides CoPilotResponse's list[Source] with the camelCase wire shape — see
    # the "P1.10 contract-validation fix" note in the module docstring. mypy flags
    # this as an unsound field-type narrowing (list is invariant); Pydantic itself
    # doesn't enforce LSP on field overrides, and this is the only way to fix the
    # wire shape without editing the frozen Source model — safe in practice since
    # nothing constructs an AiQueryResponse with plain Source instances.
    sources: list[SourceOut] = Field(default_factory=list)  # type: ignore[assignment]
